import { PT_DICT, PT_TRANSLATIONS } from './language-base';

// 🇫🇷 Dictionnaire de traduction : Français
export const FR_DICT: typeof PT_DICT = {
  RQS_DSP_CORE: 'RQS DSP CORE',
  SUBTITLE: 'Glissez la piste ici pour la validation acoustique',
  DROP_PROMPT: 'Déposez le fichier .WAV ici',
  OR_CLICK: 'ou cliquez pour parcourir vos fichiers',
  FILE_INTERCEPTED: 'chargé.',
  EXTRACT_STEMS: '🧬 EXTRAIRE 6 STEMS (ISOLATION MULTIPISTE)',
  DISSECTING: '🧬 Demucs sépare la matrice acoustique en 6 canaux... Cela peut prendre quelques minutes. Ne fermez pas cet onglet.',
  REACTOR_PROCESSING: '⚙️ RQS Reactor traite la télémétrie... Veuillez patienter.',
  MASTER_COMPLETED: '✅ Mastering terminé ! [Télécharger l’audio]',
  EJECT_DECK: '⏏️ ÉJECTER LA PISTE ET VIDER LE DECK',
  SYNCHRONIZING: '⚡ Synchronisation de la matrice audio... Veuillez patienter.',
  DISSECTING_MINI: '🧬 EXTRACTION...',
  UPLOAD_FIRST_STEMS: 'Chargez une piste pour activer la séparation des stems',

  ORIGINAL: 'Original',
  MASTER: 'Master',
  VOLUME_MATCH: 'Volume Match (en cours de développement 🔧)',
  PERFIL_ACUSTICO: 'Profil acoustique (Powered by RQS DSP)',
  INTENSIDADE_MASTER: 'Intensité du mastering (Dynamic Control)',

  THUNDER: '🌩️ Thunder',
  CLEAR_SKY: '☁️ Clear Sky',
  SUNROOF: '☀️ Sunroof',
  AURORA: '🌌 Aurora',

  BAIXA: '🟢 Faible (dynamique)',
  MEDIA: '🟡 Moyenne (équilibrée)',
  ALTA: '🔴 Élevée (compétitive)',

  HEAR_TEST: '🎧 ÉCOUTER LE TEST (15 s)',
  MASTER_FULL: '🔥 MASTERISER LA PISTE COMPLÈTE',
  ANALYZING: 'Analyse...',
  PROCESSING_ACUSTICO: 'Traitement acoustique...',

  SETLIST_ENGINE: '🎛️ RQS Setlist Engine',
  MIX_DROP_PROMPT: 'Glissez vos pistes masterisées ici',
  MIX_OR_CLICK: 'ou cliquez pour ouvrir le dossier',
  TIMELINE_TITLE: 'Timeline',
  TRACKS_COUNT: 'pistes',
  CROSSFADE_TO: '↳ Crossfade vers la piste',
  SECONDS: 'secondes',
  DEPLOY_LABEL: 'Nom du fichier de déploiement (.WAV) :',
  FFMPEG_PROCESSING: '⚙️ RQS FFmpeg Engine assemble les crossfades... Veuillez patienter.',
  DEPLOY_COMPLETED: '✅ Déploiement terminé ! Le téléchargement de la setlist a démarré automatiquement.',
  IGNITE_IDLE: '🔥 LANCER LE DÉPLOIEMENT DE LA SETLIST',
  IGNITE_ACTIVE: '🔥 RENDU DE LA COMPILATION...',

  EKG_MONITOR_TITLE: '📟 MONITEUR EKG ACOUSTIQUE',
  SIGNAL_ACTIVE: 'SIGNAL AUDIO ACTIF',
  FREQUENCY_SPECTRUM: 'Analyse du spectre de fréquences',
  PHASE_CORRELATION: 'Corrélation de phase et image stéréo',

  LIMIT_EXCEEDED_ALERT: 'Limite de masterings gratuits atteinte (3 sur 3 utilisés). Passez à RQS PRO lorsque le plan sera disponible pour augmenter vos possibilités de mastering.',
  FREE_USAGE_LABEL: 'Masterings gratuits restants',
  PRO_USAGE_LABEL: 'Plan : RQS PRO',

  FOOTER_TAGLINE: 'Intelligence acoustique et ingénierie DSP pour la musique électronique et industrielle.',
  FOOTER_TELEMETRY: 'INFORMATIONS SYSTÈME',
  FOOTER_NODE: 'Région de traitement audio',
  FOOTER_COMPLIANCE: 'Références DSP',
  FOOTER_TERMS: 'Conditions d’utilisation',
  FOOTER_PRIVACY: 'Politique de confidentialité',
  FOOTER_PRICING: 'Offres payantes',
  FOOTER_SA_EAST: 'São Paulo (sa-east-1)',
  FOOTER_EBU_R128: 'EBU R128 / ITU-R BS.1770',
  FOOTER_COPYRIGHT: '© 2026 RaQuel Synths. Tous droits réservés.',
  FOOTER_CONTACT: 'Nous contacter',

};

export const FR_TRANSLATIONS: typeof PT_TRANSLATIONS = {
  LANDING_HERO_EYEBROW: 'CRÉÉ PAR RAQUEL SYNTHS // BÊTA PUBLIQUE',
  LANDING_HERO_TITLE: 'DU SIGNAL BRUT À LA SORTIE.',
  LANDING_HERO_SUB: 'Masterisez. Séparez les stems. Construisez vos sets. Diffusez votre musique.',
  LANDING_CTA_OPEN: 'OUVRIR RQS STUDIO',
  LANDING_CTA_EXPLORE: 'DÉCOUVRIR LES FONCTIONNALITÉS',
  LANDING_HERO_NOTE: 'Des outils de production musicale conçus au sein d’un véritable projet indépendant.',

  LANDING_CAP_MASTERING: 'MASTERING',
  LANDING_CAP_STEMS: 'SÉPARATION DES STEMS',
  LANDING_CAP_SETLIST: 'SETLIST ENGINE',
  LANDING_CAP_UPLINK: 'RQS UPLINK',
  LANDING_CAP_NOTE: 'Des outils développés au cœur d’un véritable projet musical.',

  LANDING_MASTER_TAGLINE: 'Finalisez la piste.',
  LANDING_MASTER_DESC: 'Analysez le loudness, générez une prévisualisation et finalisez le master dans le workflow RQS DSP Core.',
  LANDING_MASTER_ITEM_1: 'Analyse du loudness',
  LANDING_MASTER_ITEM_2: 'True Peak et télémétrie',
  LANDING_MASTER_ITEM_3: 'Profils acoustiques',
  LANDING_MASTER_ITEM_4: 'Comparaison A/B basée sur la prévisualisation',

  LANDING_SPLIT_TAGLINE: 'Récupérez chaque élément.',
  LANDING_SPLIT_DESC: 'Séparez une piste en 6 stems pour le remix, l’analyse et la reconstruction créative avec le workflow de séparation du Studio.',

  LANDING_BUILD_TAGLINE: 'Transformez vos pistes en set.',
  LANDING_BUILD_DESC: 'Organisez les pistes, configurez les crossfades et rendez une session continue avec RQS Setlist Engine.',
  LANDING_BUILD_ITEM_1: 'Organisation des pistes',
  LANDING_BUILD_ITEM_2: 'Crossfades configurables',
  LANDING_BUILD_ITEM_3: 'Rendu WAV continu',

  LANDING_DEPLOY_TAGLINE: 'Envoyez le signal.',
  LANDING_DEPLOY_DESC: 'Collez le lien de votre piste Spotify, SoundCloud, YouTube ou Bandcamp. RQS Uplink Engine génère un lien court qui tente d’ouvrir le contenu dans l’application officielle compatible et réduit les frictions des navigateurs intégrés.',

  LANDING_ORIGIN_TITLE: 'CONÇU AU CŒUR DE LA MUSIQUE.',
  LANDING_ORIGIN_TAGLINE: 'Nous utilisons les mêmes outils.',
  LANDING_ORIGIN_DESC: 'RQS Studio est né comme un ensemble d’outils internes du workflow RaQuel Synths — mastering, séparation de stems, préparation de setlists et deep links musicaux. Le système s’ouvre maintenant à d’autres créateurs.',
  LANDING_ORIGIN_CTA: 'DÉCOUVRIR RAQUEL SYNTHS',

  LANDING_PROOF_TITLE: 'ÉCOUTEZ LA DIFFÉRENCE.',
  LANDING_PROOF_DESC: 'La comparaison A/B publique sera ajoutée uniquement avec de l’audio réel et des métriques vérifiées. Aucun résultat fictif n’est utilisé comme preuve produit.',

  LANDING_PRICING_TITLE: 'COMMENCEZ GRATUITEMENT.',
  LANDING_PRICING_DESC: 'La bêta publique conserve un accès gratuit contrôlé pendant la préparation du lancement de RQS PRO.',
  LANDING_FREE_PRICE: 'BÊTA PUBLIQUE',
  LANDING_FREE_ITEM_1: '3 masterings complets',
  LANDING_FREE_ITEM_2: 'Jusqu’à 3 Uplinks actifs',
  LANDING_FREE_ITEM_3: 'Accès au workspace principal',
  LANDING_FREE_CTA: 'COMMENCER GRATUITEMENT',

  LANDING_PRO_DESC: 'RQS PRO est encore en préparation pour son lancement public. Un aperçu des tarifs et limites prévus est disponible, mais aucun abonnement payant ni checkout n’est actif.',
  LANDING_PRO_ITEM_1: 'Aperçu des tarifs localisés en BRL, USD et PLN',
  LANDING_PRO_ITEM_2: 'Limites prévues pour MASTER, SPLIT, BUILD et DEPLOY',
  LANDING_PRO_ITEM_3: 'Les abonnements payants restent désactivés pendant la bêta publique',
  LANDING_PRO_STATUS: 'APERÇU DU LANCEMENT',
  LANDING_PRO_CTA: 'VOIR LES TARIFS // APERÇU',

  PRICING: {
    eyebrow: 'BÊTA PUBLIQUE // APERÇU DES TARIFS DE LANCEMENT',
    title: 'DES TARIFS PENSÉS POUR LES ARTISTES INDÉPENDANTS.',
    subtitle: 'Commencez gratuitement. Passez à une offre supérieure lorsque RQS Studio devient une partie essentielle de votre workflow.',
    inactive: 'Les abonnements payants ne sont pas encore actifs. Rejoignez la liste d’attente pour être informé de leur disponibilité.',
    previewLabel: 'TARIFS DE LANCEMENT PRÉVUS',
    monthly: '/ mois',
    openStudio: 'OUVRIR RQS STUDIO',
    joinWaitlist: 'REJOINDRE LA LISTE D’ATTENTE',
    features: 'ORIENTATION DES FONCTIONNALITÉS',
    proposedQuota: 'Quota proposé',
    publicBeta: 'BÊTA PUBLIQUE',
    plannedAccess: 'ACCÈS PRÉVU DES OFFRES PAYANTES',
    currentBetaAccess: 'ACCÈS ACTUEL DE LA BÊTA',
    taxes: 'Les taxes applicables, le cas échéant, seront indiquées avant l’achat lorsque les offres payantes seront disponibles.',
    compareTitle: 'BÊTA ACTUELLE VS. ACCÈS PRÉVU',
    compareIntro: 'L’accès à la bêta publique reste distinct du futur découpage des offres payantes. Aucun entitlement payant n’est actif actuellement.',
    feature: 'Fonctionnalité',
    price: 'Prix',
    fullMasters: 'Full Masters',
    preview: 'Preview',
    ab: 'Comparaison A/B',
    setlist: 'Setlist Engine',
    uplink: 'RQS Uplink',
    stems: 'Séparation des stems',
    availableBeta: 'Disponible pendant la bêta publique',
    planned: 'prévu',
    waitlistTitle: 'SOYEZ INFORMÉ DU LANCEMENT.',
    waitlistIntro: 'Utilisez la liste d’attente RQS existante pour recevoir les informations de disponibilité. La préférence d’offre n’est pas encore enregistrée.',
    emailLabel: 'E-mail',
    emailPlaceholder: 'vous@exemple.com',
    sending: 'INSCRIPTION...',
    waitlistSuccess: 'Vous êtes inscrit sur la liste d’attente de lancement RQS.',
    waitlistError: 'Impossible d’ajouter cette adresse e-mail à la liste d’attente pour le moment.',
    faqTitle: 'FAQ',
    freeTagline: 'Découvrez le système.',
    masterTagline: 'Finalisez vos pistes.',
    plusTagline: 'Construisez votre workflow.',
    proTagline: 'Utilisez le Studio complet.',
    freeCurrentAccess: 'ACCÈS ACTUEL DE LA BÊTA',
    freeItem1: '3 Full Masters au total',
    freeItem2: 'Preview : comportement actuel de la bêta',
    freeItem3: 'Comparaison A/B lorsqu’elle est actuellement prise en charge',
    freeItem4: 'Setlist, Uplink et Stems disponibles pendant la bêta publique',
    masterItem1: 'Workflow MASTER',
    masterItem2: 'Outils de mastering',
    masterItem3: 'Comparaison A/B lorsqu’elle est actuellement prise en charge',
    plusItem1: 'Tout ce qui est inclus dans MASTER',
    plusItem2: 'BUILD / Setlist Engine',
    plusItem3: 'DEPLOY / RQS Uplink',
    proItem1: 'Tout ce qui est inclus dans PLUS',
    proItem2: 'SPLIT / Séparation des stems',
    proItem3: 'Workflow MASTER / SPLIT / BUILD / DEPLOY',
    independentArtists: 'POUR LES ARTISTES INDÉPENDANTS',
    fullStudio: 'STUDIO COMPLET',
    waitlistEyebrow: 'LISTE D’ATTENTE // PAS DE CHECKOUT',
    infoEyebrow: 'RQS STUDIO // INFORMATIONS',
    faq: [
      { q: 'Puis-je utiliser RQS Studio gratuitement ?', a: 'Oui. RQS Studio est actuellement en bêta publique. L’expérience Free comprend le quota actuel de mastering de la bêta, tandis que plusieurs modules du Studio restent disponibles pendant les tests.' },
      { q: 'Les abonnements payants sont-ils actifs ?', a: 'Non. Les abonnements payants, le checkout et les entitlements commerciaux ne sont pas actifs. Les cartes payantes de cette page sont uniquement un aperçu des tarifs de lancement.' },
      { q: 'Ces tarifs sont-ils définitifs ?', a: 'Non. Il s’agit de tarifs de lancement prévus et ils peuvent encore évoluer avant l’ouverture des offres payantes.' },
      { q: 'Pourquoi les prix diffèrent-ils selon la devise ?', a: 'RQS Studio utilise des tarifs localisés pour les devises prises en charge. Il s’agit de grilles tarifaires fixes et indépendantes, sans conversion automatique selon les taux de change quotidiens.' },
      { q: 'Des taxes supplémentaires seront-elles ajoutées ?', a: 'Les taxes applicables, le cas échéant, seront affichées avant l’achat lorsque les offres payantes seront disponibles. Cet aperçu ne calcule ni TVA, ni Stripe Tax, ni taxes de checkout.' },
      { q: 'Que se passe-t-il lorsque j’atteins la limite gratuite de mastering ?', a: 'La limite actuelle de la bêta bloque les nouveaux Full Masters une fois le quota gratuit consommé. Le comportement de Preview reste séparé et vous pouvez rejoindre la liste d’attente pour être informé des futures offres payantes.' },
      { q: 'RQS revendique-t-il la propriété de ma musique ?', a: 'Consultez les Conditions d’utilisation pour les règles actuelles de propriété et d’usage. Cette page de tarifs ne les remplace pas et ne les reformule pas.', legal: 'terms' },
      { q: 'Comment les fichiers audio envoyés sont-ils traités ?', a: 'Consultez la Politique de confidentialité pour les informations actuelles sur le traitement et la conservation des fichiers audio. Cette page évite volontairement de dupliquer les règles détaillées de conservation.', legal: 'privacy' },
    ],
  },

  LANDING_FINAL_TITLE: 'VOTRE SIGNAL EST PRÊT.',
  LANDING_FINAL_DESC: 'Masterisez. Séparez. Construisez. Diffusez.',

  HERO_TITLE: 'RÉÉCRIVEZ LE CODE SONORE DE VOTRE MUSIQUE.',
  HERO_SUB: 'RQS Studio est une workstation cloud intelligente conçue pour les producteurs indépendants, les DJs et les créateurs de musique générative.',
  HERO_CTA: '[ 🎛️ ENTRER GRATUITEMENT DANS LE MAINFRAME ]',
  HERO_NOTE: '*Testez vos 3 premières pistes sans inscription ni carte bancaire.',

  DSP_TITLE: 'MAÎTRISEZ L’ACOUSTIQUE DE L’IA GÉNÉRATIVE',
  DSP_DESC: 'Les musiques générées par IA (Suno/Udio) peuvent présenter de l’agressivité et des graves brouillons. Notre moteur DSP Python SciPy corrige ces problèmes acoustiques en moins de 300 millisecondes.',

  STEMS_TITLE: 'SETLIST ENGINE & SÉPARATEUR DE STEMS',
  STEMS_DESC: 'Extrayez voix, batteries et synthés dans des fichiers WAV séparés. Harmonisez automatiquement le loudness moyen d’un album selon la norme EBU R128.',

  PRICE_BETA_BADGE: '[ BÊTA FINALE // VALIDATION DU SYSTÈME ]',
  PRICE_TITLE: 'RQS PRO ARRIVE BIENTÔT.',
  PRICE_DESC: 'RQS Studio est en phase finale de tests de production. Les outils principaux sont disponibles gratuitement pour évaluation pendant la préparation du lancement public de RQS PRO.',
  PRICE_CTA: '[ 💎 RQS PRO // BIENTÔT ]',

  AB_PREVIEW_LOCK_NOTE: 'Générez une prévisualisation de 15 s pour activer la comparaison A/B.',
  AB_PREVIEW_GENERATING: 'GÉNÉRATION DE LA PRÉVISUALISATION DU MASTER...',
  BTN_GENERATE_PREVIEW: '[ ⚡ GÉNÉRER UNE PRÉVISUALISATION DE 15 SECONDES ]',
  VOLUME_MATCH: 'Volume Match',
  ORIGINAL_LABEL: 'A - ORIGINAL',
  MASTER_LABEL: 'B - MASTER PREVIEW',
  FULL_MASTER_COMPLETED_ALERT: '💎 MASTER COMPLET TERMINÉ !',

  SETLIST_ENGINE: 'RQS SETLIST ENGINE',
  MIX_DROP_PROMPT: 'Glissez vos pistes masterisées ici',
  MIX_OR_CLICK: 'ou cliquez pour ouvrir le dossier',
  VALIDATION_TITLE: '🛡️ VALIDATION DE LA SETLIST ET CONFORMITÉ',
  VALIDATION_MIN_TRACKS: '❌ Au moins 2 pistes sont nécessaires pour générer une setlist.',
  VALIDATION_NAME_REQUIRED: '❌ Le nom du fichier d’export est obligatoire.',
  VALIDATION_SR_MISMATCH: '⚠️ Des fréquences d’échantillonnage différentes ont été détectées. Le moteur effectuera un rééchantillonnage automatique à 44,1 kHz.',
  VALIDATION_BD_MISMATCH: '⚠️ Des profondeurs de bits différentes ont été détectées. La setlist sera exportée uniformément en 24 bits.',
  SUMMARY_TITLE: '📊 RÉSUMÉ ESTIMÉ DE LA SETLIST',
  SUMMARY_TRACKS: 'Pistes :',
  SUMMARY_TOTAL_SOURCE: 'Durée totale des sources :',
  SUMMARY_TOTAL_FADE: 'Durée totale des crossfades :',
  SUMMARY_EST_OUTPUT: 'Sortie estimée :',
  SUMMARY_OUT_FORMAT: 'Format de sortie :',
  SUMMARY_EST_SIZE: 'Taille estimée :',
  LOUDNESS_MATCH_LABEL: '⚡ ÉGALISATION DU LOUDNESS PERÇU :',
  LOUDNESS_OFF: 'DÉSACTIVÉE',
  LOUDNESS_PERCEIVED: 'ÉQUILIBRER LE LOUDNESS PERÇU (LUFS)',
  LOUDNESS_NORMALIZE: 'NORMALISER À LA CIBLE (-14 LUFS)',
  CROSSFADE_CURVE_LABEL: '🎚️ COURBE DE TRANSITION (CROSSFADE) :',
  CURVE_EQUAL_POWER: 'EQUAL POWER (DOUX)',
  CURVE_LINEAR: 'LINÉAIRE (FADE DIRECT)',
  CURVE_FAST_CUT: 'FAST CUT (COUPE RAPIDE)',
  PREVIEWING_TRANSITION: '🔁 LECTURE DE LA TRANSITION : PISTE',
  TRACK_LABEL: 'PISTE',
  BTN_STOP_PREVIEW: '■ ARRÊTER LA PRÉVISUALISATION',
  TIMELINE_TITLE: 'TIMELINE DE LA SETLIST',
  CROSSFADE_TO: 'FADE VERS',
  SECONDS: 'secondes',
  PREVIEW_ACTIVE: 'LECTURE...',
  BTN_PREVIEW_TRANSITION: 'ÉCOUTER LA TRANSITION (PREVIEW)',
  DEPLOY_LABEL: 'NOM DU FICHIER SETLIST MASTER (.WAV)',
  FFMPEG_PROCESSING: 'RQS TRAITE LES TRANSITIONS... VEUILLEZ PATIENTER.',
  DEPLOY_COMPLETED: 'SETLIST EXPORTÉE AVEC SUCCÈS !',
  IGNITE_ACTIVE: 'RQS_DEPLOY_ACTIF...',
  IGNITE_LIMIT_ALERT: '🔒 PLAN PRO UNIQUEMENT (>3 PISTES)',
  IGNITE_IDLE: '🔥 RENDRE ET DÉPLOYER LA SETLIST',
  SETLIST_HELPER_NOTE: 'Crée un fichier WAV continu unique avec toutes les transitions et courbes configurées.',

  SYNCING_WITH_S3_BUNKER: 'SYNCHRONISATION AVEC LE BUNKER...',
  PROTECTED_IN_BUNKER: 'PROTÉGÉ DANS LE BUNKER',
  UPLINK_TITLE: '📡 RQS UPLINK ENGINE',
  UPLINK_STATUS: 'CONNEXION STABLE',
  UPLINK_DESC: 'Acheminez vos déploiements audio. Générez des deep links intelligents pour ouvrir directement les applications de streaming compatibles et réduire les frictions de connexion.',
  UPLINK_DETECTED: '⚡ NOUVEAU DÉPLOIEMENT AUDIO DÉTECTÉ DANS LE MAINFRAME',
  BTN_INSTANT_DEPLOY: '[ DÉPLOIEMENT MARKETING INSTANTANÉ ]',
  BTN_COMPILE_LINK: '[ COMPILER LE LIEN SÉCURISÉ ]',
  UPLINK_INPUT_PLACEHOLDER: 'URL DE DESTINATION (SPOTIFY / YOUTUBE)...',

  DEPLOY_LABELURL: 'URL DE DESTINATION',
  CUSTOM_SLUG_LABEL: 'SLUG PERSONNALISÉ',
  META_PIXEL_ID_LABEL: 'META PIXEL ID (OPTIONNEL)',

  ANALYTICS_CLICKS: 'CLICS',
  ANALYTICS_CONVERSION: 'TAUX DE CONVERSION',
  ANALYTICS_PIXEL: 'STATUT DU PIXEL',
  PIXEL_ACTIVE: 'ACTIF',
  PIXEL_INACTIVE: 'INACTIF',

  uplinkTitle: 'RQS UPLINK ENGINE',
  uplinkBadge: 'DEEP LINK BYPASS ACTIVE : Accès direct',
  uplinkDesc: 'Collez le lien de votre piste Spotify, SoundCloud ou YouTube. Le moteur génère un lien court intelligent qui tente d’ouvrir le contenu directement dans l’application officielle compatible, sans demander vos identifiants de plateforme musicale.',
  urlLabel: 'URL DE LA PISTE (STREAMING)',
  slugLabel: 'SLUG PERSONNALISÉ (OPTIONNEL)',
  compileBtn: '[ COMPILER LE DEEP LINK SÉCURISÉ ]',
  copyLink: 'Copier le lien',
  copiedLink: '✓ Copié !',

  dashTitle: 'RQS UPLINK ANALYTICS & DEEP LINKS',
  activeLinks: 'Liens actifs',
  dashDesc: 'Gérez vos deep links publiés sur Instagram, TikTok, Facebook et YouTube. Suivez les clics et les sources de trafic.',
  emptyLinks: 'Aucun deep link n’a encore été compilé. Utilisez RQS Uplink Engine ci-dessus pour générer votre premier lien de suivi.',
  clicksLabel: 'Clics',
  conversionLabel: 'Conversion',
  trafficSources: 'Sources de trafic :',
  copyUrl: 'Copier l’URL',
  deleteBtn: 'Supprimer',

  UPLINK_LOGIN_REQUIRED: 'LOGIN_REQUIRED : vous devez être connecté pour créer des deep links. Connectez-vous pour continuer.',
  UPLINK_LIMIT_REACHED: 'LIMIT_REACHED : le plan Free permet jusqu’à 3 Deep Links actifs. RQS PRO proposera des limites supérieures lors de son lancement.',

  MASTER_LIMIT_REACHED: 'Limite gratuite atteinte',
  PRO_WAITLIST_NOTE: 'Rejoignez la liste de lancement RQS PRO et soyez informé lorsque l’offre sera disponible.',
  PRO_WAITLIST_CTA: '[ 🔔 REJOINDRE LA LISTE DE LANCEMENT ]',
  PRO_WAITLIST_JOINING: '[ SYNCHRONISATION... ]',
  PRO_WAITLIST_SUCCESS: 'Vous êtes inscrit sur la liste de lancement RQS PRO.',
  PRO_WAITLIST_ERROR: 'Impossible de rejoindre la liste pour le moment. Réessayez plus tard.',
};
