import { Injectable, computed, signal } from '@angular/core';

export type UiLanguage = 'en' | 'pt' | 'pl';

export const PT_DICT = {
  RQS_DSP_CORE: 'RQS DSP CORE',
  SUBTITLE: 'Arraste a faixa para homologação acústica',
  DROP_PROMPT: 'Solte o arquivo .WAV aqui',
  OR_CLICK: 'ou clique para buscar no sistema',
  FILE_INTERCEPTED: 'interceptado.',
  EXTRACT_STEMS: '🧬 EXTRAIR 6 STEMS (ISOLAMENTO MULTI-PISTA)',
  DISSECTING: '🧬 IA Demucs está dissecando a matriz acústica em 6 canais... (Pode demorar alguns minutos. Não feche a aba!)',
  REACTOR_PROCESSING: '⚙️ RQS Reator processando telemetria... Aguarde.',
  MASTER_COMPLETED: '✅ Masterização concluída! [Download áudio]',
  EJECT_DECK: '⏏️ EJETAR FAIXA E LIMPAR DECK',
  SYNCHRONIZING: '⚡ Sincronizando matriz de áudio com o Bunker... Aguarde.',
  DISSECTING_MINI: '🧬 EXTRAINDO...',
  UPLOAD_FIRST_STEMS: 'Carregue uma faixa para liberar o isolamento de Stems',
  ORIGINAL: 'Original',
  MASTER: 'Master',
  VOLUME_MATCH: 'Volume Match (Em construção 🔧)',
  PERFIL_ACUSTICO: 'Perfil Acústico (Powered by RQS DSP)',
  INTENSIDADE_MASTER: 'Intensidade da Masterização (Dynamic Control)',
  THUNDER: '🌩️ Thunder',
  CLEAR_SKY: '☁️ Clear Sky',
  SUNROOF: '☀️ Sunroof',
  AURORA: '🌌 Aurora',
  BAIXA: '🟢 Baixa (Dinâmica)',
  MEDIA: '🟡 Média (Equilibrada)',
  ALTA: '🔴 Alta (Competitiva)',
  HEAR_TEST: '🎧 OUVIR TESTE (15s)',
  MASTER_FULL: '🔥 MASTERIZAR FAIXA COMPLETA',
  ANALYZING: 'Analisando...',
  PROCESSING_ACUSTICO: 'Processando IA Acústica...',
  SETLIST_ENGINE: '🎛️ RQS Setlist Engine',
  MIX_DROP_PROMPT: 'Arraste suas faixas masterizadas aqui',
  MIX_OR_CLICK: 'ou clique para abrir a pasta',
  TIMELINE_TITLE: 'Linha do Tempo',
  TRACKS_COUNT: 'faixas',
  CROSSFADE_TO: '↳ Crossfade em direção à Faixa',
  SECONDS: 'segundos',
  DEPLOY_LABEL: 'Nomenclatura do Deploy (.WAV):',
  FFMPEG_PROCESSING: '⚙️ RQS Motor FFmpeg costurando o crossfade... Aguarde.',
  DEPLOY_COMPLETED: '✅ Deploy Concluído! O download da Setlist iniciou automaticamente.',
  IGNITE_IDLE: '🔥 INICIAR DEPLOY DA SETLIST',
  IGNITE_ACTIVE: '🔥 RENDERIZANDO MATRIZ...',
  EKG_MONITOR_TITLE: '📟 MONITORAMENTO DE EKG ACÚSTICO',
  SIGNAL_ACTIVE: 'SINAL DE ÁUDIO ATIVO',
  FREQUENCY_SPECTRUM: 'Análise de Espectro de Frequência',
  PHASE_CORRELATION: 'Correlação de Fase & Imagem Estéreo',
  LIMIT_EXCEEDED_ALERT: 'Limite de masterizações gratuitas esgotado (3 de 3 consumidas). Faça o upgrade para o plano RQS PRO para obter masterizações ilimitadas!',
  FREE_USAGE_LABEL: 'Masterizações gratuitas restantes',
  PRO_USAGE_LABEL: 'Plano: RQS PRO (Ilimitado)',
  FOOTER_TAGLINE: 'Reator de inteligência acústica e engenharia DSP para música eletrônica e industrial.',
  FOOTER_TELEMETRY: 'TELEMETRIA DO MAINFRAME',
  FOOTER_NODE: 'Nó de Rede',
  FOOTER_COMPLIANCE: 'Conformidade',
  FOOTER_TERMS: 'Termos de Serviço',
  FOOTER_PRIVACY: 'Política de Privacidade',
  FOOTER_SA_EAST: 'São Paulo (sa-east-1) - Latência Mínima',
  FOOTER_EBU_R128: 'EBU R128 & Apple ADM Compliant',
  FOOTER_COPYRIGHT: '© 2026 RaQuel Synths. Todos os direitos reservados.',
};

export const EN_DICT: typeof PT_DICT = {
  RQS_DSP_CORE: 'RQS DSP CORE',
  SUBTITLE: 'Drag the track here for acoustic validation',
  DROP_PROMPT: 'Drop the .WAV file here',
  OR_CLICK: 'or click to browse system',
  FILE_INTERCEPTED: 'intercepted.',
  EXTRACT_STEMS: '🧬 EXTRACT 6 STEMS (MULTI-TRACK ISOLATION)',
  DISSECTING: '🧬 Demucs AI is dissecting the acoustic matrix into 6 channels... (Might take a few minutes. Do not close tab!)',
  REACTOR_PROCESSING: '⚙️ RQS Reactor processing telemetry... Please wait.',
  MASTER_COMPLETED: '✅ Mastering completed! [Download audio]',
  EJECT_DECK: '⏏️ EJECT TRACK & CLEAR DECK',
  SYNCHRONIZING: '⚡ Synchronizing audio matrix with Bunker... Please wait.',
  DISSECTING_MINI: '🧬 EXTRACTING...',
  UPLOAD_FIRST_STEMS: 'Upload a track to unlock Stem isolation',
  ORIGINAL: 'Original',
  MASTER: 'Master',
  VOLUME_MATCH: 'Volume Match (Under construction 🔧)',
  PERFIL_ACUSTICO: 'Acoustic Profile (Powered by RQS DSP)',
  INTENSIDADE_MASTER: 'Mastering Intensity (Dynamic Control)',
  THUNDER: '🌩️ Thunder',
  CLEAR_SKY: '☁️ Clear Sky',
  SUNROOF: '☀️ Sunroof',
  AURORA: '🌌 Aurora',
  BAIXA: '🟢 Low (Dynamic)',
  MEDIA: '🟡 Medium (Balanced)',
  ALTA: '🔴 High (Competitive)',
  HEAR_TEST: '🎧 HEAR TEST (15s)',
  MASTER_FULL: '🔥 MASTER FULL TRACK',
  ANALYZING: 'Analyzing...',
  PROCESSING_ACUSTICO: 'Processing Acoustic AI...',
  SETLIST_ENGINE: '🎛️ RQS Setlist Engine',
  MIX_DROP_PROMPT: 'Drag your mastered tracks here',
  MIX_OR_CLICK: 'or click to open folder',
  TIMELINE_TITLE: 'Timeline',
  TRACKS_COUNT: 'tracks',
  CROSSFADE_TO: '↳ Crossfade towards Track',
  SECONDS: 'seconds',
  DEPLOY_LABEL: 'Deploy Filename (.WAV):',
  FFMPEG_PROCESSING: '⚙️ RQS FFmpeg Engine stitching crossfades... Please wait.',
  DEPLOY_COMPLETED: '✅ Deploy Completed! Setlist download started automatically.',
  IGNITE_IDLE: '🔥 START SETLIST DEPLOY',
  IGNITE_ACTIVE: '🔥 RENDERING COMPILATION...',
  EKG_MONITOR_TITLE: '📟 ACOUSTIC EKG MONITOR',
  SIGNAL_ACTIVE: 'AUDIO SIGNAL ACTIVE',
  FREQUENCY_SPECTRUM: 'Frequency Spectrum Analysis',
  PHASE_CORRELATION: 'Phase Correlation & Stereo Imaging',
  LIMIT_EXCEEDED_ALERT: 'Free mastering limit reached (3 of 3 used). Upgrade to RQS PRO for unlimited high-resolution WAV mastering!',
  FREE_USAGE_LABEL: 'Free masterings remaining',
  PRO_USAGE_LABEL: 'Plan: RQS PRO (Unlimited)',
  FOOTER_TAGLINE: 'Acoustic intelligence and DSP engineering reactor for electronic and industrial music.',
  FOOTER_TELEMETRY: 'MAINFRAME TELEMETRY',
  FOOTER_NODE: 'Network Node',
  FOOTER_COMPLIANCE: 'Compliance',
  FOOTER_TERMS: 'Terms of Service',
  FOOTER_PRIVACY: 'Privacy Policy',
  FOOTER_SA_EAST: 'São Paulo (sa-east-1) - Ultra-Low Latency',
  FOOTER_EBU_R128: 'EBU R128 & Apple ADM Compliant',
  FOOTER_COPYRIGHT: '© 2026 RaQuel Synths. All rights reserved.',
};

export const PL_DICT: typeof PT_DICT = {
  ...EN_DICT,
  SUBTITLE: 'Przeciągnij utwór, aby rozpocząć analizę i mastering',
  DROP_PROMPT: 'Upuść tutaj plik WAV lub MP3',
  OR_CLICK: 'lub kliknij, aby wybrać plik',
  FILE_INTERCEPTED: 'załadowany.',
  EXTRACT_STEMS: '🧬 WYDZIEL 6 STEMÓW',
  DISSECTING: '🧬 Demucs rozdziela nagranie na 6 ścieżek... Może to potrwać kilka minut. Nie zamykaj karty.',
  REACTOR_PROCESSING: '⚙️ RQS analizuje i przetwarza audio... Proszę czekać.',
  MASTER_COMPLETED: '✅ Mastering zakończony! [Pobierz audio]',
  EJECT_DECK: '⏏️ USUŃ UTWÓR I WYCZYŚĆ PANEL',
  SYNCHRONIZING: '⚡ Synchronizacja audio... Proszę czekać.',
  DISSECTING_MINI: '🧬 WYDZIELANIE...',
  UPLOAD_FIRST_STEMS: 'Najpierw załaduj utwór, aby odblokować separację stemów',
  ORIGINAL: 'Oryginał',
  MASTER: 'Master',
  VOLUME_MATCH: 'Wyrównanie głośności (w przygotowaniu)',
  PERFIL_ACUSTICO: 'Profil masteringu',
  INTENSIDADE_MASTER: 'Intensywność charakteru masteringu',
  BAIXA: '🟢 Niska (dynamiczna)',
  MEDIA: '🟡 Średnia (zbalansowana)',
  ALTA: '🔴 Wysoka (mocna)',
  HEAR_TEST: '🎧 ODSŁUCHAJ TEST (15 s)',
  MASTER_FULL: '🔥 MASTERUJ CAŁY UTWÓR',
  ANALYZING: 'Analiza...',
  PROCESSING_ACUSTICO: 'Przetwarzanie audio...',
  SETLIST_ENGINE: '🎛️ RQS Setlist Engine',
  MIX_DROP_PROMPT: 'Przeciągnij tutaj zmasterowane utwory',
  MIX_OR_CLICK: 'lub kliknij, aby otworzyć folder',
  TIMELINE_TITLE: 'Oś czasu',
  TRACKS_COUNT: 'utworów',
  CROSSFADE_TO: '↳ Crossfade do utworu',
  SECONDS: 'sekund',
  DEPLOY_LABEL: 'Nazwa pliku wynikowego (.WAV):',
  FFMPEG_PROCESSING: '⚙️ RQS FFmpeg renderuje przejścia... Proszę czekać.',
  DEPLOY_COMPLETED: '✅ Render setlisty zakończony.',
  IGNITE_IDLE: '🔥 RENDERUJ SETLISTĘ',
  IGNITE_ACTIVE: '🔥 RENDEROWANIE...',
  EKG_MONITOR_TITLE: '📟 MONITOR SYGNAŁU AUDIO',
  SIGNAL_ACTIVE: 'SYGNAŁ AUDIO AKTYWNY',
  FREQUENCY_SPECTRUM: 'Widmo częstotliwości',
  PHASE_CORRELATION: 'Korelacja fazy i obraz stereo',
  LIMIT_EXCEEDED_ALERT: 'Wykorzystano limit bezpłatnych masteringów (3/3). Plan RQS PRO odblokowuje nielimitowane mastery.',
  FREE_USAGE_LABEL: 'Pozostałe bezpłatne mastery',
  PRO_USAGE_LABEL: 'Plan: RQS PRO (bez limitu)',
  FOOTER_TAGLINE: 'Inteligentny mastering i narzędzia DSP dla twórców muzyki.',
  FOOTER_TELEMETRY: 'TELEMETRIA SYSTEMU',
  FOOTER_NODE: 'Węzeł sieci',
  FOOTER_COMPLIANCE: 'Zgodność',
  FOOTER_TERMS: 'Warunki korzystania',
  FOOTER_PRIVACY: 'Polityka prywatności',
  FOOTER_SA_EAST: 'São Paulo (sa-east-1)',
  FOOTER_COPYRIGHT: '© 2026 RaQuel Synths. Wszelkie prawa zastrzeżone.',
};

export const PT_TRANSLATIONS = {
  HERO_TITLE: 'REESCREVA O CÓDIGO SÔNICO DAS SUAS MÚSICAS.',
  HERO_SUB: 'O RQS Studio é uma estação de trabalho inteligente em nuvem desenvolvida para produtores independentes, DJs e criadores de música por IA.',
  HERO_CTA: '[ 🎛️ ENTRAR NO MAINFRAME DE GRAÇA ]',
  HERO_NOTE: '*Teste suas 3 primeiras faixas sem cadastro ou cartão.',
  DSP_TITLE: 'DOMINE A ACÚSTICA DA INTELIGÊNCIA ARTIFICIAL',
  DSP_DESC: 'O RQS aplica processamento DSP controlado e políticas de entrega para preparar o áudio para diferentes destinos.',
  STEMS_TITLE: 'SETLIST ENGINE & SEPARADOR DE STEMS',
  STEMS_DESC: 'Extraia vocais, baterias e sintetizadores em WAVs separados e prepare uma setlist contínua.',
  MIXLAB_TITLE: 'RQS MIXLAB: SIMULADOR DE DJ PROFISSIONAL',
  MIXLAB_DESC: 'Ferramentas de performance, setlist e áudio no navegador.',
  PRICE_TITLE: 'MASTERIZAÇÃO ILIMITADA. PREÇO DE IMPULSO.',
  PRICE_DESC: 'RQS PRO libera masterizações WAV ilimitadas e recursos avançados.',
  PRICE_CTA: '[ 💎 ADQUIRIR ACESSO RQS PRO ]',
  AB_PREVIEW_LOCK_NOTE: 'Gere uma prévia de 15s para habilitar a comparação A/B.',
  AB_PREVIEW_GENERATING: 'GERANDO PRÉVIA DA VERSÃO MASTER...',
  BTN_GENERATE_PREVIEW: '[ ⚡ GERAR PRÉVIA DE 15 SEGUNDOS ]',
  VOLUME_MATCH: 'Correspondência de Volume',
  ORIGINAL_LABEL: 'A - ORIGINAL',
  MASTER_LABEL: 'B - MASTER PREVIEW',
  FULL_MASTER_COMPLETED_ALERT: '💎 MASTERIZAÇÃO COMPLETA CONCLUÍDA!',
  SETLIST_ENGINE: 'RQS SETLIST ENGINE',
  MIX_DROP_PROMPT: 'Arraste suas faixas masterizadas aqui',
  MIX_OR_CLICK: 'ou clique para abrir a pasta',
  VALIDATION_TITLE: '🛡️ VALIDAÇÃO DE SETLIST & CONFORMIDADE',
  VALIDATION_MIN_TRACKS: '❌ Necessário pelo menos 2 faixas para gerar uma setlist.',
  VALIDATION_NAME_REQUIRED: '❌ O nome do arquivo de exportação é obrigatório.',
  VALIDATION_SR_MISMATCH: '⚠️ Sample rates diferentes detectados. O motor fará resample automático.',
  VALIDATION_BD_MISMATCH: '⚠️ Bit depths inconsistentes detectados. A saída será padronizada.',
  SUMMARY_TITLE: '📊 SUMÁRIO ESTIMADO DA SETLIST',
  SUMMARY_TRACKS: 'Faixas:',
  SUMMARY_TOTAL_SOURCE: 'Tempo Total de Fontes:',
  SUMMARY_TOTAL_FADE: 'Tempo Total de Crossfade:',
  SUMMARY_EST_OUTPUT: 'Saída Estimada:',
  SUMMARY_OUT_FORMAT: 'Formato de Saída:',
  SUMMARY_EST_SIZE: 'Tamanho Estimado:',
  LOUDNESS_MATCH_LABEL: '⚡ EQUALIZADOR DE LOUDNESS PERCEBIDO:',
  LOUDNESS_OFF: 'DESATIVADO',
  LOUDNESS_PERCEIVED: 'EQUILIBRAR PERCEBIDO (LUFS)',
  LOUDNESS_NORMALIZE: 'NORMALIZAR AO ALVO (-14 LUFS)',
  CROSSFADE_CURVE_LABEL: '🎚️ CURVA DE TRANSIÇÃO:',
  CURVE_EQUAL_POWER: 'EQUAL POWER (SUAVE)',
  CURVE_LINEAR: 'LINEAR (FADE DIRETO)',
  CURVE_FAST_CUT: 'FAST CUT (CORTE RÁPIDO)',
  PREVIEWING_TRANSITION: '🔁 REPRODUZINDO TRANSIÇÃO: FAIXA',
  TRACK_LABEL: 'FAIXA',
  BTN_STOP_PREVIEW: '■ PARAR PRÉVIA',
  TIMELINE_TITLE: 'LINHA DO TEMPO DA SETLIST',
  CROSSFADE_TO: 'FADE PARA',
  SECONDS: 'segundos',
  PREVIEW_ACTIVE: 'REPRODUZINDO...',
  BTN_PREVIEW_TRANSITION: 'OUVIR TRANSIÇÃO',
  DEPLOY_LABEL: 'NOME DO SETLIST MASTER (.WAV)',
  FFMPEG_PROCESSING: 'RQS PROCESSANDO TRANSIÇÕES... AGUARDE.',
  DEPLOY_COMPLETED: 'SETLIST EXPORTADA COM SUCESSO!',
  IGNITE_ACTIVE: 'RQS_DEPLOY_ATIVO...',
  IGNITE_LIMIT_ALERT: '🔒 APENAS PLANO PRO (>3 FAIXAS)',
  IGNITE_IDLE: '🔥 RENDER & DEPLOY SETLIST',
  SETLIST_HELPER_NOTE: 'Gera um único arquivo contínuo WAV com as transições configuradas.',
  SYNCING_WITH_S3_BUNKER: 'SINCRONIZANDO...',
  PROTECTED_IN_BUNKER: 'PROTEGIDO',
  UPLINK_TITLE: '📡 RQS UPLINK ENGINE',
  UPLINK_STATUS: 'CONEXÃO ESTÁVEL',
  UPLINK_DESC: 'Crie deep links para plataformas de streaming.',
  UPLINK_DETECTED: '⚡ NOVO DEPLOY DE ÁUDIO RECONHECIDO',
  BTN_INSTANT_DEPLOY: '[ DEPLOY DE MARKETING INSTANTÂNEO ]',
  BTN_COMPILE_LINK: '[ COMPILAR LINK SEGURO ]',
  UPLINK_INPUT_PLACEHOLDER: 'URL DE DESTINO (SPOTIFY / YOUTUBE)...',
  DEPLOY_LABELURL: 'URL DE DESTINO',
  CUSTOM_SLUG_LABEL: 'SLUG CUSTOMIZADO',
  META_PIXEL_ID_LABEL: 'META PIXEL ID (OPCIONAL)',
  ANALYTICS_CLICKS: 'CLIQUES',
  ANALYTICS_CONVERSION: 'TAXA DE CONVERSÃO',
  ANALYTICS_PIXEL: 'STATUS DO PIXEL',
  PIXEL_ACTIVE: 'ATIVO',
  PIXEL_INACTIVE: 'INATIVO',
  uplinkTitle: 'RQS UPLINK ENGINE',
  uplinkBadge: 'DEEP LINK BYPASS ACTIVE: Sem Barreiras de Login',
  uplinkDesc: 'Cole o link da sua faixa para gerar um deep link.',
  urlLabel: 'URL DA FAIXA (STREAMING)',
  slugLabel: 'SLUG PERSONALIZADO (OPCIONAL)',
  compileBtn: '[ COMPILAR DEEP LINK SEGURO ]',
  copyLink: 'Copiar Link',
  copiedLink: '✓ Copiado!',
  dashTitle: 'RQS UPLINK ANALYTICS & DEEP LINKS',
  activeLinks: 'Links Ativos',
  dashDesc: 'Gerencie seus deep links e métricas.',
  emptyLinks: 'Nenhum deep link criado ainda.',
  clicksLabel: 'Cliques',
  conversionLabel: 'Conversão',
  trafficSources: 'Fontes de Tráfego:',
  copyUrl: 'Copiar URL',
  deleteBtn: 'Excluir',
};

export const EN_TRANSLATIONS: typeof PT_TRANSLATIONS = {
  ...PT_TRANSLATIONS,
  HERO_TITLE: 'REWRITE THE SONIC CODE OF YOUR MUSIC.',
  HERO_SUB: 'RQS Studio is an intelligent cloud workstation for independent producers, DJs, and generative AI creators.',
  HERO_CTA: '[ 🎛️ ENTER THE MAINFRAME FOR FREE ]',
  HERO_NOTE: '*Test your first 3 tracks with no registration or credit card required.',
  DSP_TITLE: 'INTELLIGENT MASTERING & DSP',
  DSP_DESC: 'RQS applies controlled DSP and delivery policies to prepare audio for different destinations.',
  STEMS_TITLE: 'SETLIST ENGINE & STEMS SPLITTER',
  STEMS_DESC: 'Extract vocals, drums, and synths into separate WAV files and prepare continuous setlists.',
  MIXLAB_TITLE: 'RQS MIXLAB: PROFESSIONAL DJ TOOLKIT',
  MIXLAB_DESC: 'Performance, setlist, and audio tools in your browser.',
  PRICE_TITLE: 'UNLIMITED MASTERING.',
  PRICE_DESC: 'RQS PRO unlocks unlimited WAV mastering and advanced tools.',
  PRICE_CTA: '[ 💎 UPGRADE TO RQS PRO ]',
  AB_PREVIEW_LOCK_NOTE: 'Generate a 15s preview to enable A/B comparison.',
  AB_PREVIEW_GENERATING: 'GENERATING MASTER PREVIEW...',
  BTN_GENERATE_PREVIEW: '[ ⚡ GENERATE 15-SECOND PREVIEW ]',
  VOLUME_MATCH: 'Volume Match',
  ORIGINAL_LABEL: 'A - ORIGINAL',
  MASTER_LABEL: 'B - MASTER PREVIEW',
  FULL_MASTER_COMPLETED_ALERT: '💎 FULL MASTER COMPLETED!',
  SETLIST_ENGINE: 'RQS SETLIST ENGINE',
  MIX_DROP_PROMPT: 'Drag your mastered tracks here',
  MIX_OR_CLICK: 'or click to open the folder',
  VALIDATION_TITLE: '🛡️ SETLIST VALIDATION & COMPLIANCE',
  VALIDATION_MIN_TRACKS: '❌ At least 2 tracks are required.',
  VALIDATION_NAME_REQUIRED: '❌ Export filename is required.',
  VALIDATION_SR_MISMATCH: '⚠️ Different sample rates detected. The engine will resample automatically.',
  VALIDATION_BD_MISMATCH: '⚠️ Inconsistent bit depths detected. Output will be standardized.',
  SUMMARY_TITLE: '📊 ESTIMATED SETLIST SUMMARY',
  SUMMARY_TRACKS: 'Tracks:',
  SUMMARY_TOTAL_SOURCE: 'Total Source Time:',
  SUMMARY_TOTAL_FADE: 'Total Crossfade:',
  SUMMARY_EST_OUTPUT: 'Estimated Output:',
  SUMMARY_OUT_FORMAT: 'Output Format:',
  SUMMARY_EST_SIZE: 'Estimated Size:',
  LOUDNESS_MATCH_LABEL: '⚡ PERCEIVED LOUDNESS MATCH:',
  LOUDNESS_OFF: 'DISABLED',
  LOUDNESS_PERCEIVED: 'MATCH PERCEIVED LOUDNESS (LUFS)',
  LOUDNESS_NORMALIZE: 'NORMALIZE TO TARGET (-14 LUFS)',
  CROSSFADE_CURVE_LABEL: '🎚️ TRANSITION CURVE:',
  CURVE_EQUAL_POWER: 'EQUAL POWER (SMOOTH)',
  CURVE_LINEAR: 'LINEAR',
  CURVE_FAST_CUT: 'FAST CUT',
  PREVIEWING_TRANSITION: '🔁 PLAYING TRANSITION: TRACK',
  TRACK_LABEL: 'TRACK',
  BTN_STOP_PREVIEW: '■ STOP PREVIEW',
  TIMELINE_TITLE: 'SETLIST TIMELINE',
  CROSSFADE_TO: 'FADE TO',
  SECONDS: 'seconds',
  PREVIEW_ACTIVE: 'PLAYING...',
  BTN_PREVIEW_TRANSITION: 'HEAR TRANSITION',
  DEPLOY_LABEL: 'SETLIST MASTER FILENAME (.WAV)',
  FFMPEG_PROCESSING: 'RQS PROCESSING TRANSITIONS... PLEASE WAIT.',
  DEPLOY_COMPLETED: 'SETLIST EXPORTED SUCCESSFULLY!',
  IGNITE_ACTIVE: 'RQS_DEPLOY_ACTIVE...',
  IGNITE_LIMIT_ALERT: '🔒 PRO PLAN ONLY (>3 TRACKS)',
  IGNITE_IDLE: '🔥 RENDER & DEPLOY SETLIST',
  SETLIST_HELPER_NOTE: 'Creates one continuous WAV file with configured transitions.',
  SYNCING_WITH_S3_BUNKER: 'SYNCING...',
  PROTECTED_IN_BUNKER: 'PROTECTED',
  UPLINK_TITLE: '📡 RQS UPLINK ENGINE',
  UPLINK_STATUS: 'STABLE CONNECTION',
  UPLINK_DESC: 'Create deep links for streaming platforms.',
  UPLINK_DETECTED: '⚡ NEW AUDIO DEPLOY DETECTED',
  BTN_INSTANT_DEPLOY: '[ INSTANT MARKETING DEPLOY ]',
  BTN_COMPILE_LINK: '[ COMPILE SECURE LINK ]',
  UPLINK_INPUT_PLACEHOLDER: 'DESTINATION URL (SPOTIFY / YOUTUBE)...',
  DEPLOY_LABELURL: 'DESTINATION URL',
  CUSTOM_SLUG_LABEL: 'CUSTOM SLUG',
  META_PIXEL_ID_LABEL: 'META PIXEL ID (OPTIONAL)',
  ANALYTICS_CLICKS: 'CLICKS',
  ANALYTICS_CONVERSION: 'CONVERSION RATE',
  ANALYTICS_PIXEL: 'PIXEL STATUS',
  PIXEL_ACTIVE: 'ACTIVE',
  PIXEL_INACTIVE: 'INACTIVE',
  uplinkTitle: 'RQS UPLINK ENGINE',
  uplinkBadge: 'DEEP LINK BYPASS ACTIVE',
  uplinkDesc: 'Paste your track URL to create a deep link.',
  urlLabel: 'TRACK URL (STREAMING)',
  slugLabel: 'CUSTOM SLUG (OPTIONAL)',
  compileBtn: '[ COMPILE SECURE DEEP LINK ]',
  copyLink: 'Copy Link',
  copiedLink: '✓ Copied!',
  dashTitle: 'RQS UPLINK ANALYTICS & DEEP LINKS',
  activeLinks: 'Active Links',
  dashDesc: 'Manage deep links and metrics.',
  emptyLinks: 'No deep links created yet.',
  clicksLabel: 'Clicks',
  conversionLabel: 'Conversion',
  trafficSources: 'Traffic Sources:',
  copyUrl: 'Copy URL',
  deleteBtn: 'Delete',
};

export const PL_TRANSLATIONS: typeof PT_TRANSLATIONS = {
  ...EN_TRANSLATIONS,
  HERO_TITLE: 'NADAJ SWOJEJ MUZYCE GOTOWE BRZMIENIE.',
  HERO_SUB: 'RQS Studio to inteligentne narzędzia masteringu, setlist i DSP dla producentów, DJ-ów i twórców muzyki generowanej przez AI.',
  HERO_CTA: '[ 🎛️ WEJDŹ DO RQS STUDIO ]',
  HERO_NOTE: '*Pierwsze 3 mastery możesz przetestować bez karty.',
  DSP_TITLE: 'INTELIGENTNY MASTERING I DSP',
  DSP_DESC: 'RQS stosuje kontrolowane przetwarzanie i polityki dostarczania, aby przygotować materiał do streamingu, klubu lub festiwalu.',
  STEMS_TITLE: 'SETLIST ENGINE I SEPARACJA STEMÓW',
  STEMS_DESC: 'Wydziel wokal, perkusję i pozostałe stem-y oraz przygotuj ciągłą setlistę.',
  MIXLAB_TITLE: 'RQS MIXLAB: NARZĘDZIA DJ',
  MIXLAB_DESC: 'Narzędzia performance, setlist i audio działające w przeglądarce.',
  PRICE_TITLE: 'MASTERING BEZ LIMITU.',
  PRICE_DESC: 'RQS PRO odblokowuje nielimitowany mastering WAV i funkcje zaawansowane.',
  PRICE_CTA: '[ 💎 PRZEJDŹ NA RQS PRO ]',
  AB_PREVIEW_LOCK_NOTE: 'Wygeneruj 15-sekundowy podgląd, aby włączyć porównanie A/B.',
  AB_PREVIEW_GENERATING: 'GENEROWANIE PODGLĄDU MASTERU...',
  BTN_GENERATE_PREVIEW: '[ ⚡ GENERUJ PODGLĄD 15 S ]',
  VOLUME_MATCH: 'Wyrównanie głośności',
  ORIGINAL_LABEL: 'A - ORYGINAŁ',
  MASTER_LABEL: 'B - PODGLĄD MASTERU',
  FULL_MASTER_COMPLETED_ALERT: '💎 PEŁNY MASTER GOTOWY!',
  SETLIST_ENGINE: 'RQS SETLIST ENGINE',
  MIX_DROP_PROMPT: 'Przeciągnij tutaj zmasterowane utwory',
  MIX_OR_CLICK: 'lub kliknij, aby otworzyć folder',
  VALIDATION_TITLE: '🛡️ WALIDACJA SETLISTY',
  VALIDATION_MIN_TRACKS: '❌ Potrzebne są co najmniej 2 utwory.',
  VALIDATION_NAME_REQUIRED: '❌ Podaj nazwę pliku wynikowego.',
  VALIDATION_SR_MISMATCH: '⚠️ Wykryto różne sample rate. Silnik wykona resampling.',
  VALIDATION_BD_MISMATCH: '⚠️ Wykryto różne bit depth. Wyjście zostanie ujednolicone.',
  SUMMARY_TITLE: '📊 PODSUMOWANIE SETLISTY',
  SUMMARY_TRACKS: 'Utwory:',
  SUMMARY_TOTAL_SOURCE: 'Łączny czas źródeł:',
  SUMMARY_TOTAL_FADE: 'Łączny crossfade:',
  SUMMARY_EST_OUTPUT: 'Szacowane wyjście:',
  SUMMARY_OUT_FORMAT: 'Format wyjściowy:',
  SUMMARY_EST_SIZE: 'Szacowany rozmiar:',
  LOUDNESS_MATCH_LABEL: '⚡ WYRÓWNANIE ODCZUWALNEJ GŁOŚNOŚCI:',
  LOUDNESS_OFF: 'WYŁĄCZONE',
  LOUDNESS_PERCEIVED: 'WYRÓWNAJ GŁOŚNOŚĆ (LUFS)',
  LOUDNESS_NORMALIZE: 'NORMALIZUJ DO -14 LUFS',
  CROSSFADE_CURVE_LABEL: '🎚️ KRZYWA PRZEJŚCIA:',
  CURVE_EQUAL_POWER: 'EQUAL POWER (ŁAGODNIE)',
  CURVE_LINEAR: 'LINEARNA',
  CURVE_FAST_CUT: 'FAST CUT',
  PREVIEWING_TRANSITION: '🔁 ODSŁUCH PRZEJŚCIA: UTWÓR',
  TRACK_LABEL: 'UTWÓR',
  BTN_STOP_PREVIEW: '■ ZATRZYMAJ',
  TIMELINE_TITLE: 'OŚ CZASU SETLISTY',
  CROSSFADE_TO: 'PRZEJŚCIE DO',
  SECONDS: 'sekund',
  PREVIEW_ACTIVE: 'ODTWARZANIE...',
  BTN_PREVIEW_TRANSITION: 'ODSŁUCHAJ PRZEJŚCIE',
  DEPLOY_LABEL: 'NAZWA PLIKU SETLIST MASTER (.WAV)',
  FFMPEG_PROCESSING: 'RQS RENDERUJE PRZEJŚCIA... PROSZĘ CZEKAĆ.',
  DEPLOY_COMPLETED: 'SETLISTA WYEKSPORTOWANA!',
  IGNITE_ACTIVE: 'RENDEROWANIE...',
  IGNITE_LIMIT_ALERT: '🔒 TYLKO PLAN PRO (>3 UTWORY)',
  IGNITE_IDLE: '🔥 RENDERUJ SETLISTĘ',
  SETLIST_HELPER_NOTE: 'Tworzy jeden ciągły plik WAV z ustawionymi przejściami.',
  SYNCING_WITH_S3_BUNKER: 'SYNCHRONIZACJA...',
  PROTECTED_IN_BUNKER: 'ZABEZPIECZONE',
  UPLINK_TITLE: '📡 RQS UPLINK ENGINE',
  UPLINK_STATUS: 'POŁĄCZENIE STABILNE',
  UPLINK_DESC: 'Twórz deep linki do platform streamingowych.',
  UPLINK_DETECTED: '⚡ WYKRYTO NOWY PLIK AUDIO',
  BTN_INSTANT_DEPLOY: '[ SZYBKI DEPLOY MARKETINGOWY ]',
  BTN_COMPILE_LINK: '[ UTWÓRZ BEZPIECZNY LINK ]',
  UPLINK_INPUT_PLACEHOLDER: 'URL DO SPOTIFY / YOUTUBE...',
  DEPLOY_LABELURL: 'URL DOCELOWY',
  CUSTOM_SLUG_LABEL: 'WŁASNY SLUG',
  META_PIXEL_ID_LABEL: 'META PIXEL ID (OPCJONALNIE)',
  ANALYTICS_CLICKS: 'KLIKNIĘCIA',
  ANALYTICS_CONVERSION: 'KONWERSJA',
  ANALYTICS_PIXEL: 'STATUS PIXELA',
  PIXEL_ACTIVE: 'AKTYWNY',
  PIXEL_INACTIVE: 'NIEAKTYWNY',
  uplinkTitle: 'RQS UPLINK ENGINE',
  uplinkBadge: 'DEEP LINK ACTIVE',
  uplinkDesc: 'Wklej adres utworu, aby wygenerować deep link.',
  urlLabel: 'URL UTWORU',
  slugLabel: 'WŁASNY SLUG (OPCJONALNIE)',
  compileBtn: '[ UTWÓRZ DEEP LINK ]',
  copyLink: 'Kopiuj link',
  copiedLink: '✓ Skopiowano!',
  dashTitle: 'RQS UPLINK ANALYTICS',
  activeLinks: 'Aktywne linki',
  dashDesc: 'Zarządzaj linkami i statystykami.',
  emptyLinks: 'Brak utworzonych linków.',
  clicksLabel: 'Kliknięcia',
  conversionLabel: 'Konwersja',
  trafficSources: 'Źródła ruchu:',
  copyUrl: 'Kopiuj URL',
  deleteBtn: 'Usuń',
};

@Injectable({ providedIn: 'root' })
export class LanguageService {
  readonly currentLang = signal<UiLanguage>('en');

  readonly t = computed(() => {
    if (this.currentLang() === 'pt') return PT_DICT;
    if (this.currentLang() === 'pl') return PL_DICT;
    return EN_DICT;
  });

  readonly tr = computed(() => {
    if (this.currentLang() === 'pt') return PT_TRANSLATIONS;
    if (this.currentLang() === 'pl') return PL_TRANSLATIONS;
    return EN_TRANSLATIONS;
  });

  constructor() {
    this.detectLanguage();
  }

  setLanguage(lang: UiLanguage): void {
    this.currentLang.set(lang);
    if (typeof window !== 'undefined') {
      window.localStorage.setItem('rqs_language', lang);
    }
  }

  private detectLanguage(): void {
    if (typeof window === 'undefined') return;

    const stored = window.localStorage.getItem('rqs_language');
    if (stored === 'en' || stored === 'pt' || stored === 'pl') {
      this.currentLang.set(stored);
      return;
    }

    // Product contract: English is the deterministic first-run language.
    // Browser locale must never silently override the primary UI language.
    this.currentLang.set('en');
  }
}
